# This file contains summarized aesthetic descriptions
aesthetics = [
("2 Tone, ska, Rude Boy, Ska, record label, Rude Boys, rudeboy, rudie, rudy"),
("2000s Virtual Singer, Hatsune Miku, VOCALOID boom, wallpapers"),
("2010s Internet, Creepypasta, flash games, Scene, Frutiger Aero"),
("2014 Girly, room decor trends, foods, brands, visuals, girly Tumblr"),
("2014 Tumblr, Morute, Delicate Sweet, Dollette, Nymphet, Coquette"),
("2020s E-Kid, TikTok, Pinterest, social media platforms, fashion style"),
("2K1, 2K1, Minivan Rock, throwback jerseys, Dirty Flirty Style, 2K5 era"),
("2K5, McBling, television and fashion aesthetic, Bohemian trend"),
("2K7, music videos, 2K7, television shows, music video aesthetic, films"),
("50s Suburbia, suburbia, suburbs, television shows, horror genre"),
("8-Bit, animated sprites, design element, text, Atari, Virtual Pets, NES"),
("80 Thousand, Synthwave, Vaporwave, aesthetics, visual and fashion motifs"),
("80s Heartthrob, aviator sunglasses, bomber jackets, leather gloves"),
("90s Cool, Bullet Time, Oakley glasses, bullet proof vests, Bullet Time"),
("Abstract Tech, circuit patterns, design motifs, user interfaces"),
("Acid Design, graphic design, Acid House, smiley faces, Psychedelic art"),
("Acid Pixie, Biopunk, Voidpunk"),
("Acidwave, lysergic acid diethylamide, LSD, acid, hallucinogenic drugs"),
("Adventurecore, exploration, navigating the world, adventure"),
("Adventure Pulp, ancient aliens, Pulp, science fiction"),
("Aeropittura, Aeropainting, aeroplanes, Aeropittura, aeroplano"),
("Aestheticism, Aestheticism, decadence, aestheticism, Aesthetic Movement"),
("Aetherpunk, Solarpunk, punk genres, enchanted lighting, guiled gold"),
("Afrofuturism, Solarpunk, Solarpunk, Cyberpunk], Afrofuturist, Black Panther"),
("Afropunk, AfroPunk, punk and alternative subcultures, people"),
("Afro-Victorian, costume decisions"),
("After Hours, kenopsia, Liminal Space, abandoned blogs, empty game servers"),
("Agropeople, Agrocore, Sertanejo and Forró genres, agribusiness"),
("Ah Beng, Ah Lian, dyed hair, playing loud music, wearing loud fashion"),
("Alien, video games, relating with these creatures"),
("Alternative, Alt, Alternative, Grunge, Punk, (rock, Emo, dark western styles"),
("Amateur Photography, images"),
("Americana, nostalgia for an idealized past, scenery, material culture, music"),
("American Gothic, Gothic, descent into madness, gothic horror, allegorization"),
("American Pioneers, Manifest Destiny, Exodusters, Donner Party, Pioneers"),
("American Thanksgiving, charity work, watching football, parades, Thanksgiving"),
("Analog Horror, Found Footage, TV Broadcasts, VHS Tapes, EAS, Digital Horror"),
("Ancient Egypt, dynastic monarchs, art and design, (pharaohs, Egyptian art"),
("Ancient Y2K, Y2K, dungeon synth, 3D graphics, 3D renders, FantasY2K"),
("Androgynous, gender expression, Androgyny, Androgyny, sexual identity"),
("Angelcore, New Age, Judaism, devilcore, Greek paganism, angelic aesthetic"),
("Anglo Gothic, council estates, grime, council estates, coal, steel mining"),
("Angura, underground theater, Visual Kei, (アングラ"),
("Animecore, edited image collages, Cutecore, video games, Cutecore's, VOCALOID"),
("Anime New Moon, Nightcore, Technoneko2000, Trance music, galaxies"),
("Anti-Fashion, political or practical goals"),
("Antique Grunge, fashion aesthetic, vintage clothing"),
("Appalachian Gothic, TikTok"),
("Arabian Driftcore, Images of characters, layering of a woman, Saudi Drift"),
("Arabian Nights, Orientalism, Orientalism, media, romanticized portrayal"),
("Arcadecore, Synthwave, Glowwave, Dunkaroos, pizza, arcades, neon signs"),
("Aristocrat, Aristocracy, Middle Ages, Boystyle fashion, fashion style, Lolita"),
("Art Academia, sculpture, calligraphy, Light Academia, photography"),
("Artcore, synthethizers, Drum and Bass, electronic musical genre, Artcore"),
("Art Deco, Art Deco's, Art Moderne, Decopunk, Bakelite, stainless steel"),
("Art Hoe, Art Hoes, painting, flowers, Babeo Baggins, art and nature, art"),
("Artificial Nature"),
("Art in the Chapels, modern art in chapels, art movement, exhibitions"),
("Art Nouveau, Art Nouveau, Art Deco, Art Deco, fine arts, Art Nouveau"),
("Arts and Crafts Movement, arts and crafts movement, product manufacturing"),
("Asian Baby Girl, (ABG, ABG, ABGs"),
("Athlete, Athlete aesthetic, sportswear, supporting, team"),
("Atompunk, Futurama, potential dark futures, Googie"),
("Auroracore, Snowdrop, Auroracore, art pieces, fantasy media, aesthetic boards"),
("Australiana, kitschy miscellanea, contemporary style aesthetic"),
("Australian Outback"),
("Autumn, fruits, pumpkins, Fall, coats, Autumn, falling leaves"),
("Autumn Academia, pumpkins, Academia, Dark Academia, Jack O' Lanterns, reading"),
("Avant Apocalypse, neutral maximalism, fashion aesthetic, upcycling"),
("Avant-garde, New Wave, New Art, Art Nouveau, anarchism, Dadaism"),
("Babycore, Morute, Kidcore, Babycore, Softcore, Delicate Sweet, Softie"),
("Babygirl, voluntary age regression, littlespace, Soft Girl, soft girl, BDSM"),
("Back-to-School, school supplies, retail season"),
("Baddie, being conventionally attractive, beauty gurus, Instagram"),
("Bakala, Bakalas, Bakalas, Electronic Dance Music, Makineros, Mákina"),
("Ballet Academia, wings, ballets, Balletic, swans, black and white contrasts"),
("Balletcore, Coquette, Princesscore, fashion trends, ballet, practice outfits"),
("Ballroom culture, Ballroom, Ballroom, performance, dance, music, fashion"),
("Barbiecore, Lip Smackers, yacht, Lizzie McGuire, Hannah Montana, private jet"),
("Bardcore, archaism, Tavernwave, rewritten versions of the original lyrics"),
("Baroque, Barroco, barroco, pearl, art, art movement, music, art"),
("Basic Girl, Basic Girl, riffing and observation, Ugg boots, yoga pants"),
("Basque Radical Rock, (ETA, La Movida, Euskadi ta Askatasuna, RRV, Urban Rock"),
("Bastardcore, friendly images, fight or flight response"),
("Beach Bunny, RABBIT, BUNNY, bunny, Bunny, rabbit, beach bunnies, cottontail"),
("Beach Girl, Instagram, resort ads"),
("Beatnik, drug use, Beat Generation, spiritual quest, media stereotype"),
("Biker, Bikers, motorcycles, bike, appeal"),
("Bimbocore, fashion style, hyperpop, rock or punk music, body positivity"),
("Biopunk, Cyberpunk, genetic engineering, Cyberpunk, biohacking"),
("Bizarro Fiction, absurdism, satire, genre staples, literary genre"),
("Black Metal, black metal, black metal, shrieked vocals, blast beats, Bathory"),
("Bleak Crush, Grunge, McBling, inflation, Y2K, Cyber Grunge"),
("Blingeecore, Blingeecore, Glittercore, sparkles, Sigilkore, Blingee"),
("Blokecore, fashion aesthetic, Ladcore, old club uniforms, football culture"),
("Bloomcore, Bloomcore, Naturecore, Floral, flowers, gardening, gardens"),
("Blue Night, Dazecore, color palette, color palette"),
("Bodikon, Gal, Amekaji, Gyaru, bodycon, Gyaru, Otachidai Gyaru, City Pop"),
("Bohemian, social and cultural movement, strong ethnic elements, fashion style"),
("Bombardier, Bombardieri, Cocalar subculture, Vagabond clothing, F10, Audi A5"),
("Bon Chic Bon Genre, BCBG, fashion style, subculture, subculture, Bon Chic"),
("Bondage, Bondage, Sissification, Morute, Pet Play, Goth, graphic design"),
("Bookstore Girl, libraries, book stores"),
("Bootleg Game, AliExpress, bootleg games, hacks of video games, eBay"),
("Bosozoku, biker gangs, Yanki subculture"),
("Boujee, Baddie, Bougie, social media, hedonism, middle class, flexes"),
("Boy Next Door, relatable experiences, genuine connections"),
("Boystyle, Lolita, makeup, Ouji, Aristocrat, Dandy, Lolita, longer hair styles"),
("Brazilian Pop Bar, wine cellars, designs on popular bars, bars, Bar"),
("Breakcore, mashed and cut up breakbeats, IDM, sampling, Digital Hardcore"),
("Bright Tertiaries, Flat Design, tertiary color palette, Frutiger Aero"),
("Britpop, punk rock, indie pop, alternative rock, grunge music"),
("Bro, sports apparel, fraternities, bro culture"),
("Bronzepunk, Cyberpunk, Bronze Age"),
("Brutal Industrial, stage and graphic design aesthetic, Attitude and"),
("Bubble Bujo, beaded straps, stickers, sparkles, Keychains, photocards"),
("Bubble Goth, Walking on Air, light and dark and puts them together"),
("Bubblegum Bitch, Bimbocore, McBling, Sanriocore, Bimbocore, McBling, Baddie"),
("Bubblegum Coquette, Coquette, lollipops, cotton candy, pastries, bows"),
("Bubblegum Dance, Bubblegum Dance, video games, Dance Dance Revolution"),
("Bubblegum Witch, crystals, Bubblegum Bitch, Pastel Goth, fairy lights"),
("Burlesque, Dresden Dolls, modern burlesque"),
("Busukawaii, ��サカワ, memes"),
("Cabincore, Cottagecore, Naturecore, Adventurecore, aesthetic"),
("Cagole, Cagoles, Cagoles, word"),
("Camp, modes of speech, camp, film, drag shows, music, cult films, fashion"),
("Campcore, Dark Naturalism, Naturecore, Scoutcore, Cabincore, Adventurecore"),
("Candyland, gingerbread, cotton candy, express whimsy, candies, clouds"),
("Cani, Tukis, Nacos, Reggaeton, Canis, Canis, Canis, Choni, ��eros, Amixers"),
("Caricaturism, Caricature, art form, art form, political figures"),
("Cartelcore, Narcos, Scarface, Narcos Footage, Miami Vice, cartels"),
("Cartooncore, Animecore, Western animation, Hulu, Japanese animation, Netflix"),
("Casino, Cartelcore, Casinos, Stripcore, Stripcore, coin games, casinos"),
("Cassette Futurism, cassettes, retrofuturism, storing and transferring data"),
("Catholic Horror, exorcisms, demonic possessions, Gothic architecture, rituals"),
("Cayetana, Cayetanos, Cayetanas, Cayetano, pijos, bullfighters"),
("Changelingcore, Goblincore, Fairycore, DID, ADHD, neurodivergent"),
("Chaotic Academia, haphazard routines, studying with a passion"),
("Chav, chavs, Chavs, TikTok, class divide, Doctor Who, Little Britain, Roadman"),
("Cheiron Crush, Cheiron Studios, music video aesthetic, pop hits"),
("Cherry Emoji Twitter, CET, Bimbocore, CET, Bubblegum Bitch, Femme Fatale"),
("Chicha, Chicha, Pop Art, Baroque, Psychedelic art, Chicha art, art movements"),
("Chic Modernist, Chic, chic, Chic, chic, chic, chic"),
("Chinese New Year, Chinese lunisolar calendar, Chinese New Year"),
("Cholo, Cholos, Cholas, Cholos, Chicano, Pachuco culture, Cholos"),
("Chonga, Chonis, Cholas, Chongas, subculture, sexual liberation, subculture"),
("Choni, Chonis, Chonis, Chonis, Chonis, Raxet, Canis, Chavs, kitschy elements"),
("Christian Girl Autumn, UGG boots, ordering pumpkin spice drinks"),
("Christian Hardcore, Christcore, visual aesthetic, decorations"),
("Christmas, Xmas, commercialism, Christmas, immigration, cultural traditions"),
("Chromecore, glass, carbon fiber, Frutiger Aero, anodized aluminum"),
("Chunyu, ���欲, aesthetic, (纯欲, style"),
("Cinnamon Girl, baking, TikTok, Coquette aesthetics, Clean Girl"),
("City Pop, Vaporwave, Vaporwave, City Pop, City Pop's, Cantopop, Taeko Onuki"),
("Classic Academia, Light Academia, Dark Academia, Dark and Light Academia"),
("Classicism, politicization, ahistorical medley of very different, art"),
("Cleancore, soaps, bathtubs, Babycore, bath toys, Kidcore, clean objects"),
("Clean Girl, TikTok, social media platforms, Instagram, beauty routines"),
("Clockpunk, clocks, phonographs, typewriters, Keys, gears, clockwork"),
("Clowncore, (clussy, Clownpunk, Circuscore, mimes, NewWorldEgo, jesters"),
("Club, DJ, live music, DJ booth, dance floor, bars, pubs, entertainment venues"),
("Club Kids, Party Monster, Party Monster, Club Kid, Disco Bloodbath"),
("Cluttercore, minimalism, mess"),
("Coastal Cowgirl, Hannah Montana, juxtaposition between Western and Nautical"),
("Coastal Grandmother, simple cooking, book clubs, grandmother"),
("Cocalar, Cocalari, Bombardier, Cocalari, Cocalari, Pițipoancă, kòkalo, Manele"),
("Coconut Girl, Coquette subtype, VSCO"),
("Coffee House/Cafe, Café, warm or neutral color blends, Coffee House"),
("Coffinwood, Cottagecore, preserve and revere the past, pop culture"),
("Comfy/Cozy, TikTok, social media sites, Instagram, Light Academia"),
("Communist Chic, music videos, hammer and sickle, Juche, communism, film sets"),
("Corporate, dress codes, business attire, business attire, smart"),
("Corporate Memphis, Flat Design, user interfaces, logos, Memphis Design"),
("Cottagecore, Naturecore, (WLW, (NBLW, Warmcore, TikTok, Fairycore"),
("Cottagegore, Cottagecore, Cottagecore, Dark Academia, vintage items"),
("Coquette Academia, coquette, coquette, light academia, ballet, ballet"),
("Corporate Hippie, aesthetic and marketing tactic, Corporate Psychedelica"),
("Country, visual tropes, political propaganda, visual trope, Western"),
("Cozy Childhood Hideaway, Havencore, Hideaway spaces, escape danger"),
("C-Pop, ballads, ambient music, Chinese rock, Chinese pop, rock, popular music"),
("Crackhead, Drugcore, Crackhead, chipped fingernails, crackheads, Drugcore"),
("Craftcore, embroidery, crafted items, craft activities"),
("Cripplepunk, Crippunk, mobility aids, disability pride"),
("Crowcore, Goblincore, Cottagecore, Crowcore, Goblincore, Gremlincore"),
("Cryptid Academia, Dark Academia, Cryptidcore"),
("Cryptidcore, Cryptozoology, Sightings, Twin Peaks, Gravity Falls"),
("Cubism, art movement, music, architecture, movement, Pablo Picasso"),
("Cuddle Party, Kidcore, Cuddle Party aesthetic, aesthetics"),
("Cultcore, mind control, god complexes, religious symbols"),
("Cult Party Kei, Cult Party, Cult Party, Cult Party, sheer layers"),
("Cutecore, Kawaii, kawaii, kawaii, image edits, shadowbans, Cutegore"),
("Cyberdelic, Cyberdelia, immersion in cyberspace, Cyberpunk"),
("Cyberghetto, Cyber, Ghetto, cyberspace"),
("Cyber Grunge, Grunge, Streetwear, Y2K, pockets, mesh, silhouettes"),
("Cybergoth, Cyberpop, fashion and music, industrial dancing"),
("Cyberparadism, advanced technology, Cyberparadism, Cyberprep, Cyberparadism"),
("Cyberpop, Cyberpunk, Cybergoth, fantasy, cyber fashion, clean outline"),
("Cyberprep, advanced body modifications, Cyberpunk, cybernetics"),
("Cyberpunk, Steampunk, Cyberpunk, Vaporwave, Vaporwave, Neuromancer, Cyberpunk"),
("Cyberspace Webrooms, skeuomorphism, Old Web, Frutiger Aero"),
("Cyber Stylin', pixel dolls, dress up games, dolls, Dollz, drawings"),
("Cybervillain, shared traits amongst villains, character aesthetic"),
("Dandy, Decadence, Dandies, Dandies, Aestheticism, Dandies"),
("Danish Pastel, TikTok, TikTok, interior and graphic design aesthetic"),
("Dank Meme Voyage, memes, memes, Memes, comics, Templates, reaction memes"),
("Dark Academia, sharing photographs, Gothicism, Dark Academics"),
("Dark Aero, Frutiger Ego, aero glass, Skeuomorphism, Frutiger Aero, Mata Nero"),
("Darkcore, Shadow figures, black void, shadowy corners"),
("DarkErrorcore, Mind Murder, Mind Murder, Triggercore, Meltcore, Glitch"),
("Darkest Academia, gothic studies, Darkest Academia"),
("Dark Fantasy, Dethereal, Spriggancore, Fantasy, Fantasy"),
("Dark Gatsby, speakeasys, Dark Gatbsy, Jay Gatsby, Jay Gatsby"),
("Dark Naturalism, mixes in the natural world, darker elements"),
("Dark Nautical, Cottagecore, Cottagecore, Witchcore, Forestpunk, Nautical"),
("Dark Nymphet, photo based aesthetic, Waif aesthetic, Coquette, Nymphet"),
("Dark Paradise, photos, visually dark photos, images of serenity"),
("Dark Royaltycore, lobotomy chic, Breadtube, dark academia, dark academia"),
("Dark Y2K, Scene, Scene, Emo, Dark Y2K, grays, dark purples, dark greens"),
("Dau al Set, Abstract Art, Dadaism"),
("Daydreampunk, internet slang, Corporate Punk, modern day punk"),
("Dazecore, Urbancore, Dark Minimalism, Geek, sleepless nights"),
("Dead Inside, anime, youth subculture, anime, Tokyo Ghoul, anime, Dota 2"),
("Decopunk, Dieselpunk, Dieselpunk, VHS tapes"),
("Decora, accessories, bracelets, plastic hair accessories"),
("Deep Fried Meme, bright glowing red eyes, racist jokes, Deep Fried Memes"),
("Deep TikTok, DeepTok, TikTok, glitch effects, bright colour filters"),
("Delicate Sweet, Morute, Morute, stuffed animals, baked goods, fabric textures"),
("Denpa, visual novel, (Maladaptative Daydreaming Disorder, Visual Novel, MADD"),
("Desertwave, sand, sandstone, cactuses, leather, camels, desert"),
("Desi Romantic Academia, decorating hands with henna, painting, reading poetry"),
("De Stijl, Neoplasticism, simplified visual compositions, art movement"),
("Dethereal, Dethereal, dark aesthetic, ethereal"),
("Devilcore, moodboards"),
("Dieselpunk, diesel, steampunk, postmodern sensibilities"),
("Digital Horror, screen recordings, web games, Analog Horror, online websites"),
("Digital Oddity, Flash animations, airbrush, web comics, Webcore"),
("Diner, Diners, Glowwave, diners, diners, fast food, neon, chain restaurants"),
("Dionysism, Dionysus, wine, oiled wineskins, Dionysia, Dionysus, Dionysia"),
("Disco, Techno, City Pop, Future Funk, dance style, Electric Boogaloo"),
("Disco Polo, Italo Disco, Eurodance, Sidewalk Music, Frutiger Metro"),
("Dirty Girl, smudged eyeliner, disheveled looks, skin care routines"),
("Dokukawaii, Yami Kawaii, poison, Gurokawa aesthetic, colors"),
("Dollcore, artistic photography, image edits, transient beauty"),
("Dollette, Dollette, Coquette, Coquette, cosmetic products, floral motifs"),
("Dolly Girl, mini skirts, Peter Pan collars, frills, ribbons, laces"),
("Dolly Kei, antique dolls, Dolly Kei, fairy tales, fashion style, Kei"),
("Doodlecore, paper textures and patterns, soft rainbow colors"),
("Doomer, Doomerwave, Doomer, Wojak meme character, Shoegaze, climate change"),
("Dopamine, lift moods, colors"),
("DORFic, Abstract Tech, Fic, Frutiger Aero, Frutiger Family"),
("Downtown Girl, Coquette, Soft Grunge, Twilightcore, TikTok, Uptown Girl"),
("Dragoncore, Goblincore, coins, Crowcore, Goblins, precious stones"),
("Drain, low resolutions, Bladee, Drainer, music videos, Bladee"),
("Dreamcore, images, Weirdcore, music, videos, dreams, daydreams, media"),
("Dream Punk, anachronistic elements, whimsical elements, mental health"),
("Dreamy"),
("Dresiarz, Dresiarze, Disco, Dresiarze, Disco Polo, Dresy, tracksuits, Techno"),
("Drugcore, abusing dangerous substances"),
("Dual Kawaii, Morute, Melodycore, Kuromicore, accept both sides of themselves"),
("Dullcore, stormy and gloomy elements"),
("Dungeoncore, video games, claustrophobia, atmosphere of dungeons"),
("Dungeonpunk, Cyberpunk, Cyberpunk, Berserk, dark miserable medieval world"),
("Dutch Golden Age, independence breeding cultural pride, Painting, genre works"),
("Earthcore, Granola, Geology, creating a harmonious ecosystem, Astronomy"),
("Earthy Black Girl, West African spirituality, traditional African femininity"),
("E-Boy, TikTok app, electronics, Soft Boy aesthetic, Electronic Boys"),
("Eccentric"),
("Edgy Meme, Edgy Memes, Joke Aesthetics, hate and fear, LarpercoreThese"),
("E-Girl, Yami Kawaii, Goth Punk, Tiktok, Soft Grunge, Soft Girl, social media"),
("Electropop 08, Avantropop, Electropop, Frutiger Aero aesthetic, Recession Pop"),
("Electro-Eclectic, Futurism, art projects, Frutiger Aero, soundscapes, fashion"),
("Electro Swing, Jazz, EDM, Jazz, Electro Swing, swing, swing, House"),
("Elizabethan England, ceramics, decorative arts, sculptures, architecture"),
("ElsaGate, YTP videos, pop culture characters, social media, Kidcore, videos"),
("Emo, Hardcore Punk, dark clothing, expressive hairstyles, fashion style"),
("English Major, Creative Writing, English Literature, Dark Academia, MFA, BA"),
("Equestrian, saddles, equestrian, equestrians, horseshoes, riding on horseback"),
("Ero-Guro, Angura, (guro, (ero, art movement, grotesque nonsense, art movement"),
("Erokawa, kawaii, kawaii, erokawa, lingerie, ero, adult content"),
("Eshay, Pig Latin, slang expression, subculture, adlay"),
("Ethereal, Dreamy, Fairytale, classical dancers, Snowdrop, pixie dust, angels"),
("Ethno-Chic, raw materials, blends Chic elements, room decoration"),
("Europunk, distorted European vision, (alternative history, Ruritaniancore"),
("EXEcore, creepypastas, Ben Drowned, creepypasta imagery"),
("Expressionism, Expressionist, distorting it radically for emotional effect"),
("Fairy Academia, Dark Academia, fairies, Oberon, Titania, trick photography"),
("Fairycore, Goblincore, Goblincore, Goblincore, mushrooms, flowers, Fairycore"),
("Fairy Grunge, TikTok, Grunge, social media platforms, Kinderwhore aesthetic"),
("Fairy Kei, pastel color palette, (ファンシー"),
("Fairy Tale, Fairy tales, short story, gnomes, goblins, talking animals"),
("Fanfare, Circuses, Carnivals, carnivals, circuses, Circuses, circuses"),
("Fantasy, oral traditions, epic fantasy, Cottagecore"),
("Fantasy Astronomy, mapping constellations, divination, observatory, astrology"),
("FantasY2K, Mythpunk, Fairycore, haute couture runway looks, Fairy Grunge"),
("Farmer's Daughter, Coquette subtype, Buckle Bunny, Tiktok, Pinterest"),
("Fauvism, Impressionism, art movement, bold brushstrokes and vibrant colors"),
("Female Horror Game Protagonist Fashion, Coquette, TikTok trend"),
("Femboy, contrasting gender signifiers, femboys, gender identity"),
("Femcel Weeaboo, Breakcore, WataMote, Evangelion, Lolicore, Indie Rock"),
("Femme Fatale, Baddie, Baddie, Dark Coquette, Old Hollywood"),
("Feralcore, or becoming feral"),
("Fieldcore, Fieldcore, discovery of ancient items, geology, archelogy"),
("Figuration Narrative, Abstract Art, Pop Art, Figuration Narrative"),
("Film Noir, stark lighting, existential philosophy, cynical characters"),
("Flamenco, Sephardic Jewish culture, dance"),
("Flapper, Flappers, Flappers, Flappers, casual sex, Smoking"),
("Flat Design, rounded shapes, Cyber Minimalism, website user interfaces"),
("Flop TikTok, FlopTok, TikTok, TikTok, Stan Twitter videos, Flop TikTok"),
("Floral Academia, Bloomcore, Pastel Academia, Light Academia, Green Academia"),
("Foodie, foodie, alcoholic beverages, food, color combinations"),
("Forestpunk, Goblincore, cottagecore, Cryptidcore, naturecore, solar panels"),
("Fotonight Web, Frutiger Aero, low quality image montages"),
("Four Colors, color palette, Bright Tertiaries, flat humanist designs, teal"),
("French It Girl, fashion aesthetic, Girl"),
("French Girly, Instagram, indie brands, Epine, Girly Kei, luxury brands"),
("French Provincial Style, rustic characteristics, room decoration"),
("Frutiger Aero, glass, bubbles, water, Windows Aero, Frutiger fonts"),
("Frutiger Aurora, rays, aurora, Auroras, aurora, spirals"),
("Frutiger Eco, Solarpunk, Frutiger Aero, Cyberparadism, Frutiger Aero"),
("Frutiger Metro, bloom elements, gradient blocks, Frutiger, Vector Vomit"),
("Funwaacore, Funwaa, Gumcels, Funcel, Gumwaacore, Gumwaacore, Funwaa, Funcels"),
("Furry, cartoons, furry characters, furry characters, Kidcore, wolf character"),
("Future Funk, Vaporwave's, Future Funk, Vaporboogie, Vaporwave, Synth Funk"),
("Gabber, fat and distorted kicks, electronic musical genre, Mokums, tempos"),
("Gachimuchi, exaggerated movements and suggestive poses, memes and remixes"),
("Gamblecore, Gamblecore, slot machines, Phony Bureaucracy, meme aesthetic"),
("Game Night, Monopoly, Chess, WH40K, Battleship, junk food"),
("Gamercore, video games, controllers, accessories"),
("Gamine"),
("Gangsta Rap, Gangsta, gangsta, Gangsta, Gangsta, gangster, hip hop, Crips"),
("Gardencore, Bloomcore, Bloomcore, Groundcore, Gardencore, Goblincore, Soggy"),
("Geek, pursuit, technology, slang term, nerd"),
("Gesugao, AMV, (MMVs, facial expressions, facial expression"),
("Gen X Soft Club, urban typography, Y2K Futurism movement, futurist optimism"),
("Gen Z Maximalism, TikTok, minimalist aesthetic, Instagram"),
("Ghostcore, Voidpunk, cemeteries, ghosts, legends and ghost stories"),
("Girl Crush, Teen Crush, Rave, edgy delivery, style and aesthetic"),
("Girl-Next-Door, female archetype and fashion aesthetic, norms"),
("Girly Girl, Coquette, Bimbocore, Barbiecore, Softgirl, floral prints, ruffles"),
("Girly (Japanese, Girly, Girly, Girly, Girly, lace, ribbons, ruffles"),
("GiscardPunk, Giscardpunk, graphic design, modernism, Cassette Futurism"),
("Glam Girl, boujee, Baddie aesthetic, use of status symbols, Glam girl"),
("Glamorous Los Angeles, fame"),
("Glam Rock, cabaret, platform shoes, Slade, Mud, glitter, Gary Glitter, Sparks"),
("Glassmorphism, Flat Design, Flat Design, Glassmorphism, Glassmorphism"),
("Glitchcore, Mind Murder, edited and distorted, Rainbowcore, visual aesthetic"),
("Global Village Coffeehouse, GVC, Mission School aesthetic, coffeehouses"),
("Gloomcore, appreciate the quiet through dim surroundings, nature"),
("Glowwave, blacklight, neon lights, Cuddle Party, UV light, raving"),
("Goblin Academia, rocks, Goblincore, copious shiny objects, shrubbery"),
("Goblincore, moss, Goblins, Goblin, plants, mud, mushrooms, Goblins, snails"),
("Golden Age of Detective Fiction, upper class characters, mystery fiction"),
("Golden Hour, lens flare, palm trees, flowers, sunrises"),
("Goofcore, comically oversized clothing, Goofcore, fashion trend, Goofycore"),
("Googie, comic books, Raygun Gothic, spacesuits, intergalactic adventure"),
("Gopnik, Gopniks, Dizelaši, fashion style, Dresiarz, meme culture, subcultures"),
("Gorecore, Devilcore, gore, Hatecore, blood, death, murder, freaky visuals"),
("Goth, WGT, Gothic, Deathrock, Bauhaus, Joy Division, Grufti"),
("Gothabilly, hellbilly, Tiger Army, Psychobilly icons, HorrorPops, Cramps"),
("Gothcore, metalcore, metalcore, metalcore, metalcore, gothic rock"),
("Gothic, pointy arches, flying buttresses, ghosts, vampires, video games"),
("Gothic Lolita, style of Lolita"),
("Goth Punk, Visual Kei fashion, (ゴスパンク, Punk, Goth and"),
("Grandmillenial, embroidered linens, Laura Ashley prints, prep culture"),
("Greaser, Greasers, combing back hair, Raggare, hair wax, greasers, hair gel"),
("Green Academia, Goblincore, social sciences, collecting of trinkets, poetry"),
("Grifes, clothing, perfume, jewelry, pricy accessories, pricey materials"),
("Grime Art, dripping faces, Grime, selfies, drawing over familiar images"),
("Grindhouse, Grindhouses, previews and interludes, Grindhouse"),
("Gross-Out Horror, evoke feelings of disgust and discomfort, Horror, Horror"),
("Groundcore, Groundcore's, Groundcore', Naturecore, Adventurecore"),
("Grunge, cigarettes, grunge, Pearl Jam, Soundgarden, neon lights"),
("Gurokawa, Pastel Goth, Yami Kawaii, Gothic elements"),
("Gyaru, challenge societal norms, bold makeup, Gal, beauty standards"),
("Hacker, computer hacking, Old Web, freedom of information, Hacker culture"),
("Harajuku Fashion, Kawaii, Decora, Harajuku, Lolita, fashion styles, fashion"),
("Hair Metal, melodic hooks, guitar solos, riffs, Glam Metal, shred, Hair Metal"),
("Hands Up, Dancecore, Jumpstyle, Hardstyle, Trance, DJ Gollum, Basshunter"),
("Halloween, celebration of departed souls, elements"),
("Hallyu, Khonminam, boy bands, shoujo and bishounen, Korean drama shows"),
("Happycore, Traumacore, Happycore, bright stickers, photos of cute animals"),
("Hatecore, Nazi Punk, Satanism, NS Punk, Violencecore, hardcore punk music"),
("Hauntology, sampling, library music, evoke deep cultural memory"),
("Haute Couture"),
("Health Goth, biotechnology, bionic body parts, rendered environments"),
("Heatwave, fire, exposed metal, glowing things"),
("Heisei Retro, Jojifuku, Kidcore, Heisei Retro, Yume Kawaii fashion style"),
("Heistcore, heists, Cat Burglar, heists, data, art, historical documents"),
("Hellenic, Classicism, creating altars, Dark Academia, Greek mythology"),
("Helvetica Aqua Aero, bubbles, gloss, Helvetica Aqua, water, Aquacore"),
("Hermaphroditus, Salmacis, androgynous being, nymph Salmakis, them"),
("Hermitpunk, surviving in nature, Naturecore, Cottagecore, Adventurecore"),
("Heroic Realism, Realism, Realism, Realistic art style, Heroic Realism"),
("Heroin Chic, Coquette, Waif, Pastel Grunge, dark red lipstick, Lobotomy Chic"),
("Hexatron, Cyberpunk, DORFic, hexagons, DualSense controller, 3D graphics"),
("HexD, Sextrance, Surge, Krushclub, Frutiger Aero, Emo, electronic dance music"),
("High School Dream, Stereotypes, School SweetheartsSchool, teen angst"),
("Hikecore, adventurecore, Adventurecore, adventurecore, jungles, hiking"),
("Hip-Hop, break dancing, synthesized beats and sounds, rhythmic beatboxing"),
("Hipness Purgatory, loose drawings, loose aesthetic movement"),
("Hippie, youth movement, beatniks, counterculture"),
("Hipster, Rockabilly, alternative subcultures, alternative subcultures, Punk"),
("Historical Americana, create national culture, Manifest Destiny"),
("Himbocore, fashion style, bling, high fashion"),
("Holo, Holo, Skeuomorphism, Skeuomorphism, Dark Skeuomorphism, shading"),
("Holosexual, crystals, knives, glitter, sunglasses, edited swirled holographic"),
("Hollywood Regency, lacquer, Regency Moderne, interior designer"),
("Home 2K, Home 2K, interior design aesthetic, design aesthetic"),
("Honeycore, honey, honey, honey, Honey, honey, honey, honey, mint, honey"),
("Horror, inducing feelings of horror and terror, genre of speculative fiction"),
("Horror Academia, libraries, archives, Darkest Academia, Dark Academia"),
("Hot Topic, fashion and products"),
("Hydrogen, Hydrogen, lunar imagery, zeppelins, retrofuturism, float"),
("Hypebeast, Hypebeasts, Hypebeasts, Hype Beasts, bouncers, streetwear"),
("Hyperborean, Dementia Praecox, Schizoposting, Esoteric Nazism"),
("Hyperpop, EDM, traditional pop, extreme pitching and warping, synths"),
("Icepunk, Icepunk, Cleancore, Icecore, Icepunk, seapunk, seapunk, seapunk"),
("Imaginarium, Psychedelica, combines many different elements, Craftcore"),
("Imperial Romanov, Romanov Dynasty"),
("Impressionism, Impressionist, Impressionist, impression of a painting"),
("Incel, Incels, emotional instability, incels, mental health challenges"),
("Indicolite, water, Indicolite, diamonds, sparklecore, statues"),
("Indie, shoegaze, indie aesthetic, Indie Sleaze, indie movie, Indie Kid"),
("Indiecraft, stop motion, video games, Hipness Purgatory, 3D illustrations"),
("Indie Kid, Kidcore, Skater, Cuddle Party, TikTok, skater, Indie"),
("Indie Sleaze, imprecise eyeliner, Pop Art, Superflat Pop, MySpace"),
("International Typographic Style, Flat Design, Minimalism, graphic design"),
("Internet Academia, Dark Academia, Chaotic Academia, Art Academia"),
("Internet Awesomesauce, Doge, galaxies, laser eyes, junk food, rainbows"),
("Isocore, isopod, crustacean, text or doodles, core elements"),
("I-Spy, stop motion, lamps, crafts, Trinketcore, video games"),
("Italian Futurism, Art Deco, surreal art, artistic and social movement"),
("Italian Mafia, Mafia, Mafia, drug trafficking, Mafia, Mafia, Boujee aesthetic"),
("Italo Disco, dance, electronic dance music, space disco, electronica, pop"),
("Itasha, stickers, Otaku style, bags, drawings, computer cases, aircraft"),
("Japanese New Left, civil rights movement, Zengakuren, New Left"),
("Jejemon, altered spelling and grammar, text messages, social media"),
("Jersey Shore, modern aesthetic, internet meme, Jersey Shore"),
("Jirai Kei, Yandere, subculture, subculture and aesthetic, fashion"),
("Jock, Prep, jocks, Goth, Nerd, sports and physical fitness"),
("Joyride, mental health issues, depression"),
("Juggalo, Juggalos, Juggalos, Juggalos, juggala, Ice Cube, Clowncore, fursuit"),
("Jumpstyle, Jumpen, Jumpstyle, Jumpstyle's, jumping, dance style, viral videos"),
("Junglecore, waterfalls, plants, treefrogs, creatures, leopards, orangutans"),
("Jungle Grunge, Grunge, string and woodwind instruments"),
("Karasu Zoku, fashion trends, (烏族, violent gangs, (モードファッション, fashion"),
("Kawaii, adult sexuality with cuteness, Erokawa"),
("Kawaii Gamer, TikToks, Kawaii, Otaku, unboxing merchandise, kawaii gamers"),
("Kawaii Warrior, Poster Gal, Poster Gal, Sparkledogs, anthropomorphic animals"),
("Kidcore, Decora, Nostalgiacore, Babycore, cartoons, soft kawaii fashion"),
("Kid Science, paleontology, DNA, mathematics, tours, astronomy"),
("Kimoicore, Kimoicore, kimoi, surrealism, Weirdcore, mania, horror, Gurokawa"),
("Kinderwhore, Kinderwhore, Kinderwhore, Babes in Toyland, child prostitution"),
("Kingcore, Princecore, Queencore, Princecore, Woodland Goth, Forestpunk"),
("King Gas, oil and gas, pollution, poverty, patriotism"),
("Kiwiana, kiwi, Kiwiana, branded foods, Kiwi, pop culture items, toys"),
("Knightcore, Princecore, Rangercore, combat and nature visuals"),
("Kogal, Kogals, Nanchatte Seifuku, Kogals, Kogals, Kogals, Gyaru Seifuku"),
("Korean Cozy Beige, Instagram accounts, images of domesticity, Pinterest"),
("Krushclub, EDM, pixelated imagery, Low Poly visuals, Frutiger Aero"),
("Kuromicore, Kuromiota, Melodycore, Yami Kawaii, Jirai Kei, fashion styles"),
("Labcore, Vaporwave, Science Academia, monochrome black and whites"),
("Larme Kei, hairstyles, hair and makeup, glitter, LARME"),
("Larpercore, roleplay, AGS, cyberbullying, usernames, extortion, usernames"),
("La Sape, sapeurs, sape, French slang word"),
("Las Movidas, countercultural movements, visual arts, fashion, film"),
("Laser Grid, airbrushed chrome effects, chrome, grid motif, glass block walls"),
("Late 2000s Elementary School, fictional works, food, toys, fads"),
("Light Academia, Dark Academia, Light Academia’s, Dark Academia"),
("Lightcore, light figures, darkcore, dark shadow figures, light rooms"),
("Ligne Claire, comics, minimal shading, Tintin, cartoons, Clear Line"),
("Lil Girl, Kidcore, Kidcore, Kawaii, bubblegum pop songs"),
("Liminal Space, linoleum tilings, liminal spaces, ceiling tiles"),
("Lit Kid, Academia aesthetic, Kidcore, literature"),
("Live Laugh Love, decals, word art wall signs, script fonts"),
("Lobotomy Chic, Indie Sleaze, exploring femininity, waif aesthetic"),
("Lo-Fi, Vaporwave, Dazecore, Vintage, Cartooncore, Animecore, genre of music"),
("Lolailo, Lolailos, Rumba, Lolailos, Flamenco, makeup, drag queen, (belts"),
("LOLcore, Minimalism, fashion style, maximalist elements, glitter"),
("Lolita, LiveJournal, lace, Lolita, Lolita, ruffles, Goth, cosplay, Lolitas"),
("Long Island, Long Island, local culture"),
("Lounge, Las Vegas"),
("Lovecore, TikTok, Lovecore, crushing on someone from afar, Lovecore"),
("Low Poly, 3D art, video games, Modernism, improve performance"),
("Lunarpunk, witchcraft, Solarpunk, illusion, renewable energy, nature"),
("Mad Scientist, visual aesthetic, practical writing necessities, villainy"),
("Magical Girl, Magical Girls, Sailor Moon, Magical Girl, color coded costumes"),
("Maid, Maid, Maidcore, maid, aesthetic, themed restaurants, aesthetic, anime"),
("Major League Gaming, MLG, MLG, MLG, MLG, Deep Fried Memes, Surreal Memes"),
("Mall Ninja, Weeaboos, Weeaboo, Weeaboos, Mall Ninjas, weapons training, anime"),
("Mallsoft, Mallwave, Liminal Space, Vaporwave, Mallcore"),
("Malwarecore, fake download buttons, adware, fake installers"),
("Mandrake, Funkeiro, herbaceous plant, Nóia, favelas, carioca funk culture"),
("Manguebeat, maracatu performances, mangroves, crab"),
("Manly Men, leather, cool details, beanies, sunglasses, dark colors, bland"),
("Mary Sue, Gary Stu, (Parody Sue, Internet fandoms, animation memes"),
("Maximalism, Minimalism, design style"),
("McBling, Y2K, UrBling, Frutiger Aero aesthetics, Facebook page, Y2K, Y2K"),
("Meatcore, body horror, organs, mutilation, raw meat, blood, flesh, aesthetic"),
("Med-Tech Visions, digital scientific stock images, computing"),
("Medicalcore, paraphernalia, coping mechanism, aesthetic"),
("Medieval, Middle Ages, art history sources, art and architecture"),
("Medieval Fantasy, Fantasy, Fantasy"),
("Memphis Design, Vaporwave, Future Funk, Synthwave, bright neon colors"),
("Memphis Lite, Memphis, Memphis Design, interior design, graphic design"),
("Mermaid, merman, storms, drowning, Mermaids, fantasy creatures, mythology"),
("Messy French It Girl, Dom Perignon, Chanel pumps, French It Girl, It Girl"),
("Metal, Heavy metal, Acid rock, Black Sabbath, Doom metal, Grunge, Power metal"),
("Metalcore, Thrash, breakdowns, blast beats, crust punk, moshing"),
("Metalheart, Trendwhore, Depthcore, Cyberpunk aesthetic"),
("Metrosexual, metrosexuals, in flashy fashion styles, grooming and appearance"),
("Miami Metro, Tropical and Metrosexual Aesthetics, Metrosexual Aesthetic"),
("Midwest Emo, Emo, Emo, Midwest, Emo"),
("Midwest Gothic, exaggerations of Midwestern traditions"),
("Milipili, Milipilis, Lollapalooza, looks, personal names, Pilar"),
("Military, Paramilitary, SWATcore, fashion and visuals, LE agencies, SWATpunk"),
("Milk, Grunge, Milk's, darker imagery, milk tea, darker colors, Subgenres"),
("Mind Murder, Mind Murder, web animation characters, TFcore"),
("Miniature, badges, rocks, spoons, collecting various types of miniatures"),
("Minimalism, Suprematism, simple living, rejection of consumerist trends"),
("Minivan Rock, alternative rock, grunge, Y2K era"),
("Miscellaneous Academia, wasting time with rabbit holes"),
("Mizuiro, Tenshi Kawaii, Tenshi Kawaii, Jirai Kei, Otaku culture, Jersey Maid"),
("Mob Wife, Clean Girl, Clean Girl, popular media, aesthetic and fashion trend"),
("Mod, Lambretta, freakbeat, modern jazz, rhythm and blues, ska, soul, jazz"),
("Modernism, state of mind, Postmodernism, fragmentation of culture"),
("Modernisme, Gesamtkunstwerk, Art Nouveau, Art Nouveau"),
("Moe, characters that create emotions of affection and adoration"),
("Moe Swag, edits, Moe Swag, anime characters, meme, meme aesthetic, Gangsters"),
("Monstercore, Devilcore, Werewolf, Cryptidcore, Vampire, aesthetic, aesthetics"),
("Monumentality, aesthetic of monumentality, large things, big things"),
("Mori Kei, Mori, Mori Girl"),
("Morute, Traumacore, Traumacore, Morute, eating disorders, physical disability"),
("Motomami, MOTOMAMI, social media, motorbikes, fashion visuals, music"),
("Mossy, fungi, Forestpunk, shacks, Mushroomcore, cabins, Cottagecore, huts"),
("MS Paint, Microsoft Paint, digital drawings, Old Web, solid colors and lines"),
("MTV Green Sky, music videos, music videos, motion pictures, VH1 Sepia Sky"),
("Mulchcore"),
("Musical Academia, learning instruments and vocal techniques, Theatre Academia"),
("Mythpunk, Woodland Goth, radical reinterpretation, Elfpunk, urban fantasy"),
("Nanchatte Seifuku, pretend school uniform, learning, Preppy"),
("Naturecore, Cottagecore, Bloomcore, plants, forests, flowers"),
("Nautical"),
("Nautical Fantasy, Oceanpunk, Oceanpunk, Oceanpunk, fantasy elements"),
("Neon Noir, Synthwave, stylized visuals, neon text"),
("Necrotrap, SoundCloud, aggressive beats, SoundCloud, Necro Trap, suicide"),
("Neo-Breton Style, architectural style, modern materials and techniques"),
("Neo-Celtic, revival of ancient Celtic cultures practices and traditions"),
("Neo-Pop, Pop Art, cartoons, New Pop, Superflat, Lowbrow, art movements"),
("Neo-Romanism, Neoclassicism, judicial system, Sandalpunk, Bronzepunk"),
("Neo-Tokyo, Solarpunk, Solarpunk, Cyberpunk, cyberpunk, cyberpunk, Cyberpunk"),
("Neo-Tribal, tattoos, Cybertribal, band logos, album cover arts, crosses"),
("Neo-Vikings, elements of Ancient Norse culture, Space Vikings"),
("Nerd, slacks, glasses, Nerds, high socks, board games, braces, video games"),
("Nerdcore, science fiction, computer technology, YTCracker, tabletop games"),
("Neubrutalism, Neubrutalism, contrasting color palettes, Neo Memphis"),
("Neumorphism, Claymorphism, Neumorphism, Flat Design, design language"),
("New Age, yoga, meditation, massage, Dreamcatchers, environmentalism"),
("New Beat, Darkwave, New Beat, Techno, Front 242, Electronic Body Music, House"),
("New England, New Hampshire, Rhode Island, Vermont, Massachusetts"),
("New England Gothic, demons, liminal space, ghosts, witches"),
("New Figuration, art movement, Nueva Figuración"),
("New Hollywood, movies, music"),
("New Money, Old Money, Old Money, Old Money, Boujee, salary, business profits"),
("New Romantic, Synthpop, Cyberpunk, Synthwave, Khonminam, LiveAid, New Dandies"),
("New Spanish Catholic Girl, Oaxacan ruffles, religious statues, TikTok"),
("New Wave, Punk, punk, punk, angular guitar lines, keyboards, visual style"),
("Night Luxe, Night Luxe, Boujee, Diva bars, That Girl, That Girl"),
("Nintencore, Pikmin, Kirby, Animal Crossing, Metroid, Super Mario, Pokémon"),
("Normcore, dressing neutrally, Basic, standing out, cultural references"),
("Northern Irish Muralism, murals, murals, political and historical symbology"),
("Northern Soul, rare and obscure records, music and dance movement"),
("Northerness, living in the north, aesthetic, the old ways, the wilderness"),
("Nostalgiacore, video games, comics, snacks, books, trends, music, fashion"),
("Noucentisme, Neoclassicism, Art Nouveau, Art Nouveau, Modernisme, Cinquecento"),
("Nuclear, gas masks, hazmat suits, lands in ruins, nuclear power"),
("Nu-Goth, darkwave, dark EBM artists, Deathrock, Witch House, Goth, Goth"),
("Nu-Metal, grunge, hip hop, alternative rock, grunge, Scene music, funk"),
("Nu-Punk, Riot Fest, personal struggle"),
("Ocean Academia, Academia aesthetic, oceanography, marine biology"),
("Ocean Grunge, Vaporwave, Grunge, Witch House, Witch House, sunken ships"),
("Oceanpunk, Seapunk, Oceanpunk's, steampunk, traverse the sea"),
("Office Siren, Bayonettacore, Dark Academia, TikTok"),
("Offlinecore, gramophones, analog technology, analog technology"),
("Olderbrothercore, TikTok, Older Brother, older brothers"),
("Old Hollywood, movies, music, draw, fashion"),
("Old Meme, trollface, Facebook, memes, memes, forums, Imgur, Old Memecore"),
("Old Money, WASP"),
("Opium, Opium, Vamp, rage trap album, subgenre of streetwear"),
("Oshare Kei, visual kei, dressing up in colorful costumes, hairclips"),
("Otaku, Otaku, otaku, Wota, Wota, Weeaboo, glasses, otaku, weeaboo, Hikikomori"),
("OtoMAD, (YTPMV, Gachimuchi wrestlers, video games, video platform, anime"),
("Pale Grunge, VSCO, black and white grids, galaxy prints, fandom merchandise"),
("Paleocore, dinosaurs, paleontology, dinosaurs"),
("Palewave, muted and pale colors, light wash jeans, white sneakers, Black"),
("Paramilitary, Gendarmerie, Tacticool, Civil Defence, SWATcore, video games"),
("Party Animal, raves, house parties, drinking"),
("Pastel Academia, pastelacademia, social medias, pastel color palettes"),
("Pastel Gore, candy, gory artwork, slime, blood, pastel colours, organs"),
("Pastel Goth, Lookbook, fashion style, kawaii aesthetic, sweet pastel elements"),
("PC-98, visual novels, dithering, eroge, personal computers, art style"),
("Pearly, pearls, pearl, Boujee inspirations, Nautical, Angelcore"),
("PEEPS, thrifting, ghost Pokémon trainers, upcycled clothing, Goth style"),
("Peoplehood, moodboards, artworks, quotes from literature, poetry"),
("Perky Goth, goth, Perky Goths, goth, black clothing, themes"),
("Petcore, Petcore, Kidcore, petcore, kemonomimi characters, birds"),
("Picniccore, gingham patterns, Picniccore, picnics, pastries"),
("Pijo, Fresas, Gomelos, Cayetanas, Pijos, Pijos, Cayetanos, Postus, Myrreys"),
("Pink Parisian, old Hollywood movies, luxury brands"),
("Pink Pilates Princess, Balletcore, Pinterest Coquette, working out"),
("Pink Princess, Pink Princess, Dollette aesthetic, Silver, color palette, gold"),
("Pin-up, Cheesecake models, Beefcake models, Gibson Girl drawings"),
("Pirate, studying maps and constellations, sketching, sea travel, Piratecore"),
("Pixelboard, pixel art, pixel art, building a fictional country"),
("Pixel Cutie, pixel art, light colors, soft orange, lilac, light blue, pink"),
("Pixel Medieval Fantasy, videogames"),
("Pixel UI, design language, graphical user interfaces, UI elements, pixels"),
("Pixelscape, pixel art, web design, isometric pixel art, online games"),
("Pixiecore, bubbles, Goblincore, succulents, Fairycore, Goblincore, dirt"),
("Plaguecore, bird masks, cloaks, bloodletting, Plague Doctors"),
("Plant Mom, flowers, succulents, plants, raise various plants"),
("Playboy, Boujee aesthetic, fast cars, tailored suits, Playboy aesthetic"),
("Poetcore, awareness and acceptance of emotions and vulnerability, of poetry"),
("Pont-Aven School, art movement, simplified forms, Synthetism art movement"),
("Politicalwave, Laborwave, Fashwave, Vaporwave"),
("Poolcore, images of pools, water, 3d renders, liminal spaces, tiles, art"),
("Pop Art, Abstract Expressionist, Abstract Expressionism, advertising"),
("Pop Kei, Decora aesthetic, brightly colored clothing"),
("Poppare, Decora, Håkan Poppare, Glitter Poppare, suspenders, BDpopare"),
("Popular Preppy, TikTok, Roblox, preppy, fashion style, online design games"),
("Post-Apocalyptic, cybernetic revolt, plague, nuclear holocausts"),
("Post-Impressionism, Georges Seurat, Vincent van Gogh, art movement"),
("Post-Punk, Goth, Shoegaze, Dark wave, No wave, Synthwave, Sex Pistols"),
("Post-Rock, song structure, sound texture, harmonies, drones, melody"),
("Poster Gal, Poster Galalso, Y2K Chibi, pop culture"),
("Prairie, wheat, flowers, cattle, grasslands, Pioneer, boho aesthetic, works"),
("Precisionism, Immaculates, art movement, art movement, Aeropittura"),
("Prehistoric, bones, cave paintings, dinosaurs, Paleocore, mammoths, dinosaurs"),
("Preppy, Prep, preps, Jock, Preppie, Goth, Nerd, high school stereotypes"),
("Pre-Raphaelite, Modern Art, Mannerist style"),
("Pride flags, moodboard, pride flags, stimboard, gender or sexual identity"),
("Princecore, Royalcore, Princesscore, Princecore, Ouji, MLM"),
("Princesscore, Pink Princess, looking like, princess"),
("Prisoncore, Prison, prison"),
("Progressive Academia, Academia, progressive traditionalism, Classic Academia"),
("Proto-Flat Web, minimalistic cartoon design, animations, HTML5 Flat Design"),
("Psychedelica, distorted electric guitar, sitar, magic mushrooms, mescaline"),
("Psychonaut, meditation, altered states of consciousness, lucid dreaming"),
("PSY-OP Girl, TikTok, propaganda, influence the behavior"),
("Punk, direct action, rock music, punk, punk rock, ethos, ethos, music"),
("Purism, purism, art movement, Cubist movement"),
("Quality Tumblr, Basic Girl, VSCO, Quality Tumblr's, films and novels, quotes"),
("Queencore, Royalcore, Princesscore, Princesscore, matriarchal figures"),
("Queer Academia, art, learn about the people, expression"),
("Queercore, Homocore, cultural and social movement, Punk subculture"),
("R&B, electronic music, record production style, Rhythm and Blues"),
("Racaille, Lacoste sportswear, Lacoste cap, tight jeans, Nike TN sneakers"),
("Rage HD, LED stages, stage and graphic design aesthetic"),
("Rainbowcore, Scene, Glowwave, Decora, Holosexual, Kidcore, Old Web"),
("Rainy Day, tension, create feelings of sadness, drama, melancholy, rainy"),
("Randumb, Scene, meme aesthetic, Emo, acting silly in public"),
("Rangercore, Adventurecore, Dungeons and Dragons, Tolkien books"),
("Ravencore, Goblincore, Crowcore, Goblincore, collecting items of interest"),
("Raver, Raves, Techno, Ravers, Bassline, digital audio, electronic dance music"),
("Raxet, Choni, diamonds, crop tops, Choni, Raxets, tracksuits, slippers"),
("Raygun Gothic, comic books, spacesuits, intergalactic adventure"),
("Real Life Super Hero, dressing up like comic book character, RLSH, Kidcore"),
("Rebel Academia, rebellion against the school system, Darkest Academia"),
("Red Academia, Academia, Gryffindor, reading, Academia, academia aesthetic"),
("Regency, empire waists, elaborate courtship rituals"),
("Reggaetonero, Reggaetoneros, Reggaeton, Reggaetoneros, Reggaeton"),
("Renewable Corporate Futurism, (RCU, Solargraphic, Stecoffism, global warming"),
("Renovador Movement, renew the visual arts, art movement"),
("Retro-Futurism, Atompunk, Steampunk, futurism, Cyberpunk, Raygun Gothic"),
("Revcore, blood, Grotesque imagery, Roblox shirt, gore and stickmen characters"),
("Revengecore, emo, My Chemical"),
("Rivethead, electronic body music, industrial music, industrial rock music"),
("Roaring 20s, fashion, traditional practices, literature, art, music"),
("Robotcore, robots, robots, robots, robots, aesthetic"),
("Robotics Kids, robotics, robotics, robotics, robotics, robotics, robotics"),
("Rock, melodic basslines, brash drums, strong guitars, drummer, bassist"),
("Rockabilly, country music, rock, country music, visual clichés"),
("Rocketpunk, space exploration, NASApunk, hard science fiction"),
("Rockstar GF, Rockstar aesthetics, Dark Coquette, Indie Sleaze"),
("Rococo, curvy shapes, painting, Architecture, interior design, Baroque"),
("Roguecore, Knightcore, Rangercore, close combat, Dungeons and Dragons"),
("Rollerwave, Atompunk, Vaporwave, Outrun, LaserDisc, RadioShack"),
("Romanesque, Antique, Gothic art, Massive walls, rounded arches, art style"),
("Romantic Academia, Light Academia, Dark and Light Academia, light academia"),
("Romantic Goth, Woodland Goth, Goth, Goth, Goth, Vampire, Goth, Fairy Goth"),
("Romanticism, Nationalism, rationalism, materialism, Romanticism"),
("Romantic Italian, masked balls, fashion culture, appreciation of the arts"),
("Rotcore, Morute, rot, Dirtcore, Rotcore, rundown buildings, Decaycore"),
("Royalcore, silk, taffeta, wool, velvet, fur, Royalcore, sumptuary laws"),
("Rubberhose, hose, rubber hose, animation style, flexible rubber hoses"),
("Rustic, Gaucho culture, rustic themes, aesthetic, aesthetic, aesthetic, farms"),
("Sacricore, Queercore"),
("Sad Beige, ornaments, Sad Beige, tree, visual aesthetic, decorations, colors"),
("Sadpeople, Traumacore, Traumacore, blood, sexual imagery, Sadenbies"),
("Saint Patrick's Day, dressing up as a leprechaun, wearing green and shamrocks"),
("Salon Kei, (サロン系"),
("Salvagepunk, Scavenged Punk, Junkpunk, technology and culture, scavenged junk"),
("Sandalpunk, motor vehicles, Bronzepunk, Sandalpunk, Cyberpunk, radios"),
("Sanriocore, Hello Kitty, Sanrio characters"),
("Scandi Girl Winter, interior design, minimalist and cozy design principles"),
("Scene, Scenecore, Scenecore, Emo, Scenesters, Hyperpop, Hardcore bands"),
("Scene Tween, scene, Teenpunk, fusion of kidcore and scene, scene culture"),
("Science Academia, academic aesthetics, academic aesthetics"),
("Scottish Highlands, Albacore, Highlandcore, Skara Brae, Scotlandcore"),
("Scoutcore, braiding hair, bead crafts, Campcore, hiking, earning patches"),
("Scrapbook, bullet journaling, collage artwork, scrapbooking, scrapbooks"),
("Scrapper, scrap, physical combat, fight, subgenres, fighter"),
("Seapunk, Seapunk, Vaporwave, Future Funk, Vaporwave, Vaporwave, ocean sounds"),
("Seiz Breur, visual arts, art movement, art movement, mass media, fine arts"),
("Selkiecore, Dark Nautical, Mermaidcore, rocky beaches, jagged shorelines"),
("Shamate, dark makeup, religious symbols, dog collars, Emo, Visual Kei, Scene"),
("Shanzhai, (山寨, contemporary use, counterfeit, imitation"),
("Shibuya Punk, street gangs, graffiti, various media"),
("Shiny Suit 97, Cheiron Crush, Caribbean carnivals, music video aesthetic, Sky"),
("Shironuri, geishas, stage actors, white face paint, makeup, fashion"),
("Shoe Diva, Pink Parisian, commercial products and media, Girly Girl aesthetic"),
("Shoegaze, textural distortion, effect pedals, delay, distortion, reverb"),
("Shoujo, large and detailed eyes, art style, Japanese manga, slender figures"),
("Sigilkore, stuttering beat and vocal cuts, Tread, bitcrush effect, HexD"),
("Sigma, glamorization of serial killers, Incels, Better Call Saul"),
("Signalism, Signalizam, art movements, art and poetry, Serbian art and poetry"),
("SK8, Grunge, establish this aesthetic, Emo, editing photography, Affliction"),
("Silicon Dreams, CGI animations, surreal visuals"),
("Silkpunk, Steampunk, Dandelion Dynasty, chinese science fiction"),
("Simplecore, MS Paint, fonts, art, simple art, MS Paint drawings, drawing"),
("Silly, TikTok, memes, wacky graphics, Instagram, (X"),
("Skater, graffiti, skateboards, fisheye lens, skateboard, jeans"),
("Skeuomorphism, Flat Design, user interface, (UI, interior design"),
("Skinheads, skinhead, skinhead, skinheads, skinhead, Ska, Red Action"),
("Slam Pop"),
("Slimepunk, Vaporwave, heavy sampling, Seapunk, toxic waste, Mountain Dew"),
("Sloanie, Sloane, Sloanes, Sloanie, Sloane Ranger, Square, Lone Ranger"),
("Sleepycore, Yume Kawaii, Sleepcore, kawaii imagery"),
("Slutcore, Bubblegum Bitch, Bubblegum Bitch, bimbo, slut"),
("Snackwave, unhealthy food"),
("Snow Bunny, Bunny, snow, Snow Bunny, snow, snowshoe hare, Bunny, snow bunny"),
("Snowdrop, winter, snow"),
("Socialist Realism, Realism, art movement, idealized realistic art"),
("Soft Apocalypse, decline of technology, solar, renewable energy sources"),
("Soft Colonial Wanderlust, Boho Chic, hipster trend, aesthetics"),
("Soft Countriana, onto tradition and history"),
("Soft Grunge, VSCO, black and white grids, galaxy prints, fandom merchandise"),
("Soft Indie, Indie, incorporating various elements of the original aesthetic"),
("Soft Macabre, grains, Pastel Gore, photography, messy filters"),
("Soft Morningcore, visuals, feeling a cold floor"),
("Soggy, worms, slugs, snails, frogs, toads, swamps, critters"),
("Solarpunk, steampunk's, clean energy, renewable energy, Cyberprep, cyberpunk"),
("So Retro, MS Paint aesthetic, Super Mario, Sonic the Hedgehog, Hipster"),
("Sots Art, Pop Art, Sots Art, Pop Art, Soc Art, Art, Art, Socialist Realism"),
("Southern Belle"),
("Southern Gothic, Liminal Space, tumblr, modern American iconography"),
("Soviet Bloc School, canteen glasses, metal and wood chairs"),
("Soviet Nostalgia, sympathy for the political system, works of art"),
("Sovietwave, Synthwave, Synthwave, preservations of socialism, Cold War"),
("Spacecore, astrocore, cosmic core, decor, astronomy, clothing"),
("Spanish Golden Age, Baroque, Mannerism, artistic and cultural movements"),
("Sparklecore, glitter, art, strobe lighting, DIY projects, glittery objects"),
("Spiritcore, Lunarpunk, color palette"),
("Spy Fiction, retrieve stolen information and objects, James Bond, espionage"),
("Stargirl, designer brands, teen culture, tee shirts, TikTok"),
("Starrflesh, water, water, glass, deformed animals, objects, Starflesh"),
("Steampunk, technology and designs, science fiction, steam"),
("Steelpunk, Iron Man, Mad Max, Barb Wire, Stainless Steel Rat, megatechology"),
("Stellar Scholar, glasses, quill pens, backpacks, dress shoes, fitted pants"),
("Stimwave, cutting objects, Stim toys, Supernormal Stimuli, folding"),
("Stonepunk, Stone Age, Neolithic Revolution–era technology, Flintstones"),
("Stoner, grass, kush, Stoners, smoke, Stoners, herb, cannabis, psychedelics"),
("Strega, forest witch, Goth, Goth, witch, Stregeria"),
("Stripcore, neon signage, strip clubs, Glowwave, Vaporwave"),
("Studyblr, Studytok, Studygram, music playlists, Studytube, social media"),
("Suburban Gothic, facades, supernatural beings, drug addiction, Liminal Space"),
("Sukeban, bosozoku biker gangs, fashion style, (スケバン"),
("Summer, swimming, iced tea, popsicles, juices, salads, grilled meat, martinis"),
("Summer Matsuri, Natsu Matsuri, (夏祭り, summer festivals, Summer Matsuri"),
("Superflat, Nihonga, anime, manga, pop culture, graphics"),
("Superflat Pop, McBling, animation, Frutiger Aero, funky clothing"),
("Surf Crush, graphic design, Surf Crush, award shows, Coconut Girl"),
("Surfer, Surfers, riding waves"),
("Surrealism, surreality, creating strange creatures from everyday objects"),
("Surreal Memer, Surreal meme, surreal memes, memes, memes, Surreal Memers"),
("Synthwave, Vaporwave, Vaporwave, Neon Noir, video games, pop culture"),
("Tacticool, Tacticool, cosplay, anime style illustrations and games"),
("Taisho Roman, Taisho era, Taisho, Taisho period, Taishō Romance, shift"),
("Tango, Tango, music genre and dance, aesthetic, African"),
("Teamer, Yanki, Yanki, Yanki, Gyaru, Sukeban, Bosozoku, Teamer, trashy clothes"),
("Technical Scene, Scene, motherboards, abstract or bizarre memes, typewriters"),
("Technocore, Analogpunk, Digitalpunk, analog and digital technology"),
("Technoneko2000, video streaming services, Anime characters, old techno videos"),
("Technozen, Frutiger Aero, Frutiger Aero, Golden Sky, Wii Main Menu Music"),
("Techwear, lockers, straps, clasps, Pockets, fashion style, accessories"),
("Tecktonik, Vertigo, TCK, Milky Way, Hardstyle, Jumpstyle, dance style"),
("Teddy Boys, Teds, Judies, Teddy Girls, gangs"),
("Teenage Dream, candid photographs, adults"),
("Teenagers in the Woods, supernatural entity, horror films, media"),
("Teenpunk, Teenpunk, Emo, skulls, Monster High dolls, fishnets, Avril Lavigne"),
("Teenqueen, lollipops, lip gloss, hearts, feminine fashion, red"),
("Tendercore, Nostalgiacore, Nostalgiacore, Kidcore, sheltercore, havencore"),
("Terrorwave, VHS edit, Polaroid camera, Terrorwave, censored faces with text"),
("Teslapunk, Steampunk, fictional narratives or visual styles, electric devices"),
("TGIF Crush, TGIF block, interior design aesthetic"),
("That Girl, Pinterest, Tiktok, YouTube, vloggers, beauty rituals"),
("Theatre Academia, studying dramaturgy, academic aesthetic"),
("Theatre Kid, theatre kids, acting and stage productions, kid, actors"),
("The WB Crush, Y2K era, WB, television aesthetic, Steves Peeps, WB"),
("Thonkingposting, Schizoposting memes, Gen Alpha Brainrot, Ironic Phonk"),
("Thrasher, heavy metal, thrash, Megadeth, Anthrax, thrash, thrash:, Metallica"),
("Thriftcore, furniture, thrift shops, garage sales, toys, thrift stores"),
("Tiki, hibiscus flowers, maps, Dim lighting, netted fishing floats"),
("Tinycore, Miniature, spools of thread, acorn tea sets"),
("Tomato Girl Summer, social media, aesthetic, Gen Z aesthetics, Autumn VSCO"),
("Tomboy, tomboyish, tomboyism, tomboyish, Tomboyish, tomboyish"),
("Total Afternoon Live, aesthetic"),
("Toxiccore, removal of toxicity"),
("Trad Goth, Batcave, Deathrock, Goth, darkwave, coldwave, Goth, Goth"),
("Trailer Park Princess, Bimbocore, Nymphets, McBling, Camp and Kitsch, McBling"),
("Tranquil Spa Graphics, New Age, Tranquil Serenity, Zen Tranquility"),
("Trap Metal, loud distorted 808 patterns, Death Rap, Ragecore, trap metal"),
("Trashcore, trashcore, garbage"),
("Trashy Raver, vintage technology, house parties, county fairs"),
("Traumacore, traumacore, coping mechanism, Hello Kitty, CSA, art therapy"),
("Trenchcore, Royalcore, strong bonds with your friends, clothing"),
("Trillwave, Seapunk, Trillwave, Vaporwave, Trill, music production, visual art"),
("Triple Chic, interior design, Paris Party"),
("Tropical, vegetation, natural elements, flowers, fruits, (plants, sky, sea"),
("Tropicalcore, Coquette subtype, VSCO"),
("Tropical Disco, Frutiger Metro, Synthwave, Vaporwave, palm trees, neon lights"),
("Tupinipunk, Tupiniquim, Colecionador de Mãos"),
("Tuscan Rustic, natural materials, terracotta, oak, wood"),
("Twee, TikTok, cultivation of a passion project', Hipster, Twee, Hipsters"),
("Tweencore, Kidcore, Kidcore, Animecore, Scene, Bubblegum Coquette"),
("Twilightcore, TikTok, Twilightcore, Bella Swan, Elena Gilbert, Violet"),
("Ukiyo-e, wooden printing blocks, woodblock prints, prints, paintings, prints"),
("Ukrainian New Wave, New Wave, Neoclassicism, Socialist Realism, New Wave"),
("Ultra-Realistic Meme, Photorealism, Caricaturism, meme, fictional characters"),
("Unicorncore, Unicorncore, Unicorns, flowers, finding unicorns, Lil Girl"),
("Uptown Girl, classic and tailored clothes, Downtown Girl, Downtown Girl"),
("Urbancore, graffiti, High School Dream, urban fashion, picnics, aesthetic"),
("Urban Fantasy, fantasious characters and concepts, paranormal beings, magic"),
("UrBling, McBling, McBling, flames, McBling, McBling, advanced technology"),
("Vacation Dadcore, cargo shorts, vests, style and lifestyle aesthetic"),
("Vampire, goths, goths, vampiric fashion styles, feeding on the vital essence"),
("Vanilla Girl, social media platforms, TikTok, scented candles"),
("Vaporwave, Hypnagogic Pop, electronic music, visual style"),
("Vectorcore, Vectorcore, oscilloscopes, image creation software"),
("Vectorflourish, Vectorgarden, abstract imagery, Vectorbloom, Vectorgarden"),
("Vectorheart, Frutiger Metro, Vectorbloom, Gen X Soft Club"),
("Vibrant Academia, Academia, berets, tweed, break down stigma, cardigans"),
("Victorian, Steampunk, dressing rituals, Lolita, Industrial Revolution"),
("Victorian Goth, Goth, Romantic Goth, Romantic era, Victorian fashion"),
("Victorian Urban Poverty, art, literature, photography, Urban Poverty"),
("Viking, horned helmet, pop culture, Vikings, Northerness aesthetic"),
("Villagecore, connecting with community, natural tones, muted colors"),
("Villaincore, becoming rich or famous, coping mechanism, getting revenge"),
("Vintage Americana, rockabilly, nymphet, Lana Del Rey, retro aesthetics"),
("Vintage British Sportsman, hunting, visual culture, visual culture"),
("Violencecore, embracing of taboo emotions, Lovecore, Hatecore, gore, hatred"),
("Virgo's Tears, tarot, change and grow, mystical uses, many facets of"),
("Visual Kei, traditional Japanese clothing, Punk, Glam Rock, Goth"),
("Visual Pollution, Synthwave, Cyberpunk, modern aesthetics"),
("Voidcore, empty space, nothingness"),
("Void-Meme, bass boosted audio, Void Memes"),
("Voidpunk, voidpunk, humanityTM, voidpunks, alterhumans, aromantic and asexual"),
("Vulture Culture, dying, diaphonization, crystallization, body parts, bones"),
("Waif, Dark Nymphet, Dollette, Coquette, Waif, Coquette blogger"),
("Waldorf, Wicca, Wicca, teaching style, educational style, Light Wicca"),
("Wanderlust, bipolar disorder, engagement with different cultural experiences"),
("Warmcore, Naturecore, Cottagecore, aesthetic, aesthetic"),
("Weathercore, broadcast videos, Weatherstar4000 images, Radar images, TWC"),
("Webcore, screencaps, Webcore's, social media, Vaporwave, Flat Design"),
("Weeaboo, Otaku, Weeb, weeaboos, anime, follow social media artists"),
("Weirdcore, image compression, visual images, primitive digital graphics"),
("Welwitschia Goth, Morute, dresses, dolls, butterflies, bows, blood"),
("Werewolf, transformation, horror or unnerving elements, character trope"),
("Western, Wild West, Space Western, Wild West, Space Cowboy, Weird West"),
("Wetcore, Mud, rust, fungi, moss, erosion, swamps"),
("Whimsical Coquette, Ethereal aesthetics, Cottagecore, Dollette, Fairycore"),
("Whimsicraft, saturated colors, home interiors, teacher"),
("Whimsigothic, fairytales, Gothic, Tim Burton, forms of folklore"),
("Wholesome Meme, Doge, Wholesome Memes, Internet memes, meme aesthetic"),
("Wild Child, festivals, skateboarding, carnivals, amusement parks, protests"),
("Wimmelbilderbuch, Wimmelbook, picture book, persons and objects"),
("Winter, soup, fruitcakes, ham, snowball fights, curling, hot cocoa, tea"),
("Winter Academia, Dark Academia, reading, pursuit of knowledge, research"),
("Winter Fairy Coquette, Coquette, fashion style, coquette, Coquette"),
("Witchcore, Cottagecore, magic, gem collecting, Naturecore, herbs, aesthetic"),
("Witch House, EDM, electronic musical genre"),
("Witchy Academia, Academia, witchcraft, spell casting, casting spells"),
("Wixa, WIXAPOL, Hard Dance, Gabber, Vixa, Rave, Wiksa, Wiksy, Eurotrance"),
("Wizardcore, Witchcore, magic, magic, fantasy"),
("Wizardposting, siphoning the raw energy of the ley line, Wizardcore"),
("Wonderland, Wonderland, surreal wonderland, Alice in Wonderland"),
("Word Cloud, Typography, ASCII art, cartography, Tag Clouds, word clouds"),
("Wormcore, Squirmles, Wormcore, Worm, Worm On A String, Magic Worm, Worm Time"),
("Wota, Wotaku, Otaku, Otaku, katakana form, Otaku, celebrating idols"),
("Writer Academia, poetry, fanfiction"),
("Wuxia, (comics, video games, manhua, television series, bushido, films"),
("XO, manipulation, detachment, heavy drug usage, sex, of Balloons"),
("Xpiritualism, Instagram, world culture, old net art, Instagram, spirituality"),
("Y2K, pop culture, Year 2000 problem, semantic shift, societal zeitgeist"),
("Y2K Futurism, Y2K, Vaporwave, Vaporwave's, Y2K, gradients, Y2K, Blobitecture"),
("Yakuza, Gokudō, organized crime syndicates"),
("Yami Kawaii, Yume Kawaii, cutified horror, Gurokawa aesthetic, ��みかわ"),
("Yandere, violent outbreaks, Yangire, Jirai Kei, Cutecore, archetype"),
("Yanki, Yanki, Gyaru, Sukeban, Bosozoku, Teamer, trashy clothes"),
("Yellow Academia, Academia, light academia, plants, academia aesthetic"),
("Yume Kawaii, illustrations, fantasy themes, nightmarish elements, clothing"),
("Yuppie, Yuppie, Yuppies, Yuppies, Fight Club, Sigma, designer clothing"),
("Zenitism, graphic design, visual arts, Cubism, German Expressionism, ZENIT"),
("Zombie Apocalypse, Coffinwood, Coffinwood, Zombie, zombies"),
("7 HD, Unreal Engine 3, rubble, dusty sky, video game mascots, bloom effect"),
("American Kitsch, billboards, advertisements, magazine covers, magazine covers"),
("American Tourist Traps, chain restaurants, Tourist Traps, traps"),
("Arabfunny, loud music, Surreal Memer, Surreal Memer"),
("Balkan Violence Tumblr, tumblr, aesthetic blogs, Tumblr Purge"),
("Bankara, Yanki, haikara, cloaks, Taisho Roman, long hair"),
("Beach Day, beaches, part in"),
("Black-Holed Meme, Reddit, memes"),
("Blokette, Balletcore, Indie Sleaze aesthetics, Waif"),
("B-Movie Horror, prosthetics, fake blood, effects, cheap effects"),
("Bubbleglam, silk, velvet, fur, bubbles, animal prints, faux fur, plush"),
("Buckle Bunny, belt buckles, Buckle bunnies, rodeo prizes, groupies"),
("Chicano Lowrider, pinstripes, Lowriders, Dayton wire wheels, lowriders"),
("Choco Girl, Harajuku fashions, Himekaji Gyaru, chocolate"),
("Classic Lolita, Lolita, historic fashion"),
("Constructivism, decorative stylization, constructivist"),
("Corporate Punk, industry plants, expensive clothing, punk"),
("Crustpunk, crust, Crust punk, stenchcore, extreme metal, punk rock, of music"),
("Cyberminimalism, design grid, Flat Design's, color gradients"),
("Cyberneticpunk, old work machines, Wojaks, haphazard cables"),
("Deathcore, illegible band logos, gauged ears, blast beats, breakdowns, Hair"),
("Death Metal, deathcore, deathcore, deathcore, Death Metal, tremolo picking"),
("Dollar Store Vernacular, logos, flyers, bath salt packaging"),
("Dracopunk, Dragonpunk, Dracopunk, dragons, dragons and other mythical beings"),
("Driftcore"),
("Dungeon Synth, black metal, dino synth, comfy synth, Dark Ambient music"),
("Ethereal Death, death symbols, Invertcore, inverted colors, Ethereal Death"),
("Factory Pomo, CAD, inverting colors, computer graphics, Factory"),
("Folk Punk, folk punks, Crustpunk, Queercore, punk, Cottagecore, punk"),
("Gadgetpunk, glowing parts, gears, Steampunk, circuit boards, exposed wires"),
("Gorpcore, Entropism, normcore, items"),
("Grasscore, Mosscore, Naturecore, grass, Nostalgiacore, grass, grass, grass"),
("Grotesque, arabesque, Halloween masks, weird shapes and distorted forms"),
("Haussmann Paris, modernized roads and water structures, creation of parks"),
("Hime Lolita, OTT, decorative factors, Lolita, Sweet Lolita, Classic Lolita"),
("Hi-NRG, (EDM, electronic dance music, music genre, uptempo"),
("Juminocore, Kidcore, Pinterest, TikTok[1]"),
("Kitschy, Morute, kitsch, Babycore, Trailer Park Princess, verkitschen"),
("Lagenlook, pairing clothes and statement accessories, Bohemian aesthetic"),
("Lilac Femme, sparkles, Lilac femme, Femme de lilas, lilacs, flowers"),
("Luxury, expensive minerals, exotic cars, pricey materials, wealth, Casino"),
("Melodycore, Kuromicore, Kuromicore, Dual Kawaii, Kuromicore, Babycore"),
("Memphis Rap, Gangsta Rap, Crunk, Buck, Southern Rap"),
("Mid-Century Modern, interior design, furniture design, Firebird, architecture"),
("Mothcore, corvidcore, gremlincore, plants, moths, mushrooms, earthy tones"),
("Mote Kei, appeal to the opposite sex[2], Kei, Moteru"),
("MTV 2 Overcast, music videos, MTV Green Sky, gloomy cloudy visual style"),
("Nanopunk, Biopunk, Cyberpunk, nanotechnology[1], nanotechnology"),
("Neo Baroque, Wilhelminism, Baroque Revival, Baroque Revival"),
("Onii Kei, pointed shoes, shag haircut, imported jeans, Kei, fashion style"),
("Pastel Punk, Pastel Goth, pastel punks, pastel punks, dye their hair"),
("Peaky Blinders, illegal bookmaking, racketeering, robbery, violence"),
("Phony Bureaucracy, Phony Bureaucracy, letters, broadcasts, Analog Horror"),
("Photorealism, painting, painting[1], drawing"),
("Pig in Jacuzzicore, Cleancore, meme aesthetic, Weirdcore"),
("Powwow Step, pow wow, traditional foods, regalia, electronic music, dancing"),
("Printcore, natural elements, traces, signs, farms, streets"),
("Realism, mimesis, naturalism, Realists, Realists, Romanticism, illusionism"),
("Reefwave, video games, Reefwave's, refraction, coral reefs, sea life"),
("Retro Fairycore, Fairycore, Websites, pinboards[1], yin and yang, Fairycore"),
("Romantic Chinese Village, Douyin, TikTok, Romanticized depictions"),
("Scandinavian Design, and minimalismIt"),
("School Anti-Bullying Positivity Reinforcement, SABPR, Kindness Reinforcement"),
("Sega Uranus, dual circular motif, consoles, design aesthetic"),
("Shabby Chic, baking, lace, sewing, interior design aesthetic, reading"),
("Sizz, noise, modify the subject of an image, distortion, film noir, Instagram"),
("Soviet Brutalism, khrushchevka, khrushchevka, brezhnevka"),
("Spriggancore, Spriggancore, Spriggan, Fae, Dark Fairycore"),
("Spring, baby animals, budding flowers, sow seed, plant flowers, sunshine"),
("Studyplace, studyblr, studying, reading, studying, drawing, studying"),
("Suprematism, basic geometric forms, rectangles, lines, art movement, circles"),
("Sweet Lolita, flat shoes, bell shaped skirts, lace, soft makeup looks, fruits"),
("Swenkas, fashion show, choreography, swenking, swank"),
("Swordpunk, AI, steampunk, gene recombination, holograms, mechs"),
("Takenokozoku, KEKENOKO, dance group, Shoot Tribe'[1]"),
("Telstracore, Telstra"),
("The Box 96, Cheiron Crush, Cheiron Crush, music video, black leather jackets"),
("Tinkercore, chair, makerspaces, Tinkering, robot, 3D printers, makerspaces"),
("Tumblewave, Vaporwave, slowed down loops of country songs"),
("Ultraviolet Crush, New Jack Swing, VH1 Sepia Sky, Hair Metal"),
("Utopian Scholastic, edutainment software, Frasurbane, encyclopedias"),
("VARIOUSXYZ, VHS distortion, taking odd frames of commercials, VARIOUSXYZ"),
("Vh1 Sepia Sky, music video, Sepia Sky, Ultraviolet Crush"),
("Vintage Hero, bright colors, limited palette, printing restrictions, by time"),
("Vorticism, art that expressed the dynamism"),
("Wabi-Sabi, sanbōin, acceptance of transience and imperfection, mujō, (苦, (無常"),
("Web Creep, software development, dark web, computer science, After Hours"),
("Youthquake, blush, Makeup, nude lip, Twiggy, fashion model, marketing tool"),
("2020s Gamer, furniture, electronics, design of, Twitch streaming, products"),
("American Revolution, Founding Fathers, overthrowing the British Crown"),
("Bauhaus, imitation, artistic dilettantism, school, inferior craftsmanship"),
("Color Pop, hair, colorful flowers, black and white photo, clothing, objects"),
("Corporate Grunge, Typefaces, glitch effects, collaged images"),
("Coquette, Coquette, Nymphet, Nymphet, Nymphet, makeup, girly aesthetics"),
("Cybergrunge, Cyberpunk, neon signs, Grunge, cyber street wear, Cyber Grunge"),
("English Southern Girl"),
("Grandparentcore, focusing on things we enjoy most, Grandmacore, Grandpacore"),
("Italian Renaissance, Renascimento, Medieval period, arts and cultural history"),
("Lichencore, moths, moths, Moldcore, mold, mold, parasites, dumpsters"),
("Minivoid, arranging small objects, image style, desktop wallpapers"),
("Nazi Chic, Fashwave, Synthwave, Dead Kennedys, Punk, swastika, Punk"),
("Pachuco, zoot suits, Pachuca, zoot suit, street gangs, Pachucas"),
("Peach, Softie, Modern Peach, fancy looks, colour palettes, Vintage Peach"),
("Pretty Preppy, plaid skirts, knee socks, headbands, white shirts, accessories"),
("Queer Villainy, flamboyancy, Cyberpunk, anarchic philosophies"),
("Regional Gothic, photography of towns or townspeople, streets, apartments"),
("Sharpies, Sharpie, Sharpie, skinheads, Sharpies, SHARP, gang violence, Sharps"),
("Softie, VSCO, Softies, Babycore, TikTok aesthetics, Yume Kawaii"),
("Stilyagi, zagranitsa, beatniks, zoot suiters, modern western music, hipsters"),
("Ulzzang, Ulzzang, Heeulsa, wanghong zipai, face, King Car, best, contests"),
("VSCO, family of aesthetics, edit with preset filters and tools"),
("Belgian New Beat, New Beat, New Beat, Darkwave, New Beat, New Beat, Techno"),
("Dizelaši, Dizelašice, exaggerated makeup, dyed hair, youth subculture"),
("Día De Los Muertos, Día de Muertos, Día De Muertos, Día de Muertos"),
("Españolada, film genre, Costumbrismo, film genre, Flamenco dancers"),
("Feísmo, Brutalism, TikTok, social media platforms, mixes of various materials"),
("Galician Sentimentalism, Sentimentalismo, Sentimentalist, Sentimentalism"),
("Gangstæxtemism, graphic design, album covers, promotional material"),
("Grażynacore, GIF editors, positive phrases, Karencore, meme aesthetic"),
("Mudéjar, Romanesque, Plateresque, Gothic, Gothic, Romanesque, Mudéjar"),
("Nouveau Réalisme, Abstract Expressionism, representation of everyday objects"),
("Sextrance, bitcrushed sounds, Hextrance, Crushed Trance, drum and bass"),
("VSCO Preppy, TikTok, Roblox, preppy, online design games, Preppy, Softies"),
("Yé-yé Girl, beehives, hairstyles, youth subculture, miniskirts"),
("Yōkai, Yōkai, supernatural creatures, kappa, Akuma, kitsune, Yōkaicore"),
("Pokemón, Pokemoneo, perreo, kissing with several people, Pokemones"),
("Deathrock, missing link, deathrockers, gitane demone, rozz williams, squad"),
("Mallgoth, spooky kid, myspace, wannabe goths, angelfire, shopping malls"),
("Neko, catgirls, otaku culture, childlike femininity, cat ears"),
("Neoclassicism, ancient greece, classical history paintings, classical art"),
("Nymphet, character trope, sexual situations, teenaged girl, dolores haze"),
("Riot Grrrl, queercore scene, bikini kill, indie, domestic violence"),
("Social Science Academia, marketing, video games, dark academia, geography"),
("Imperial Aztec, tetzcoco, spanish conquistadores, nahua city, teotl"),
]
